Dockerfile
Simple addition of `libbrotli-dev` package makes curl configure script autodetect support.
Fixes #1
=> Adds support for brotli content decoding

curl_ff91esr, curl_ff95
Because we send the 'Accept-Encoding: gzip, deflate, br' header we
may receive compressed content (gzip or brotli). Previously this was
handled manually in the wrapper script, however curl has a '--compressed'
flag exactly for that purpose. Add it by default to the wrapper scripts.
=> Use --compressed flag by default

firefox/patches/curl-http2-c.patch
I noticed that, while our TLS handshake was perfectly impersonating Firefox, the session was still being detected at the HTTP2 level. From my testing this PR seems to solve that. I will leave it open for a few days to let people test and comment.
=> Fix the order of HTTP2 headers in Firefox

README.md, tests/Dockerfile, tests/README.md, tests/requirements.txt, tests/signature.py, tests/signatures.yaml, tests/test_impersonate.py
Add automated testing infrastructure with tests verifying that
`curl-impersonate` has the same TLS signature as that of the
impersonated browser.
Each wrapper script (e.g. curl_chrome98) is launched to wikipedia.org
while a packet capture is running in the background. The Client Hello
is extracted from the capture, parsed and then compared to the known
browser signature.
The known signatures are stored in a YAML database.
This is an initial testing infrastructure and does not yet cover the full
network signature of `curl-impersonate`. In the future it should also
test the HTTP headers and HTTP/2 settings that `curl-impersonate`
sends as well.
=> Add automated tests to verify curl's TLS signature

README.md, chrome/Dockerfile, chrome/curl_edge98, tests/signatures.yaml, tests/test_impersonate.py
Microsoft Edge is, since 2019, based on Chromium. It has a completely
identical TLS signature to Chrome's. The only difference is in the HTTP
headers. Adding support for impersonating Edge was therefore extremely
simple.
=> Impersonate Microsoft Edge

README.md, chrome/Dockerfile, chrome/patches/curl-impersonate.patch, firefox/Dockerfile, firefox/patches/curl-impersonate.patch, tests/Dockerfile, tests/minicurl.c, tests/test_impersonate.py
This adds initial impersonation support to libcurl. It builds an additional `libcurl-impersonate.so` shared library which can replace `libcurl`.
This is WIP. TODO:
Details from the updated README:
`libcurl-impersonate.so` is libcurl compiled with the same changes as the command line `curl-impersonate`.
It has an additional API function:
```c
CURLcode curl_easy_impersonate(struct Curl_easy *data, const char *target);
```
You can call it with the target names, e.g. `"chrome98"`, and it will internally set all the options and headers that are otherwise set by the wrapper scripts. Specifically it sets:
* `CURLOPT_HTTP_VERSION`
* `CURLOPT_SSLVERSION`
* `CURLOPT_SSL_CIPHER_LIST`
* `CURLOPT_HTTPBASEHEADER` (non-standard option created for this project).
Note that if you call `curl_easy_setopt()` …
=> Add impersonation support to libcurl

README.md, chrome/curl_chrome98, chrome/curl_edge98, chrome/patches/curl-impersonate.patch
This commit makes some of the TLS options that are used for
impersonation configurable via libcurl options and command line flags to
curl-impersonate. The goal is to give more flexibility in configuring
the TLS extensions instead of hardcoding everything into the binary.
This will enable using the same binary for impersonating different
browsers (e.g. Safari).
The following options are now present:
* CURLOPT_SSL_EC_CURVES and the '--curves' flag are now usable. These
were present in the upstream curl but only for OpenSSL builds. This
commit also enables them for BoringSSL. They configure TLS extension
'supported_groups' (no. 10).
* CURLOPT_SSL_ENABLE_NPN and the '--no-npn' flags are usable. These were
present in the upstream curl but were disabled in a previous commit by
commenting out …
=> Make some of the TLS options configurable

chrome/Dockerfile, chrome/curl_safari15_3, chrome/patches/curl-impersonate.patch, tests/signatures.yaml, tests/test_impersonate.py
Support for impersonating Safari 15.3 on MacOS Big Sur, either via the `curl_safari15_3` wrapper script or by setting the `CURL_IMPERSONATE` env var to `safari15_3`.
Instead of having a separate build system for Safari, this uses the same build as Chrome (with BoringSSL). Impersonating different browsers with the same build is now possible due to much of the TLS options and extensions having been modified to be configurable via libcurl options or command line flags (In #16).
Controlling the HTTP/2 pseudo-headers order (`:path`, `:scheme`, etc.) was also needed, as Chrome and Safari use different orders. The pseudo-headers order was therefore modified to be configurable as well.
Curl patch generated from
https://github.com/lwthiker/curl/commit/0340cd8b3e0f85ba1105d75587e36c45c5b3f2bb …
=> Impersonate Safari 15.3

chrome/curl_edge98, chrome/patches/curl-impersonate.patch, firefox/curl_ff91esr, firefox/curl_ff95, firefox/patches/curl-impersonate.patch
The HTTP headers for Edge and Firefox were slightly incorrect.
curl patches from
https://github.com/lwthiker/curl/commit/ee0a67058ff5b4e3d0aaa4650feb584c68f80182
and
https://github.com/lwthiker/curl/commit/351dba44d02524c0b5df84309db593bc31143662
=> Fix Edge and Firefox HTTP headers

chrome/curl_chrome99, chrome/curl_edge99, chrome/patches/curl-impersonate.patch, tests/signatures.yaml, tests/test_impersonate.py
Add impersonation support for Chrome 99 and Edge 99 which were just released.
Their TLS signature is identical to the previous versions (98).
The only difference is in the user agents.
curl patch from
https://github.com/lwthiker/curl/commit/ca13947f003ee711367f0438693caee93ccee696
=> Impersonate Chrome 99 and Edge 99

chrome/curl_chrome98, chrome/curl_edge98, firefox/curl_ff91esr, firefox/curl_ff95
Parameters to the wrapper scripts were passed incorrectly to
the 'curl-impersonate' binary.
Resolves #18
=> Fix bug in wrapper scripts parameter passing

README.md, chrome/Dockerfile, chrome/patches/curl-impersonate.patch, firefox/Dockerfile, firefox/patches/curl-impersonate.patch
Compile libbrotli statically into curl-impersonate/libcurl-impersonate
for convenience of usage outside the container.
=> Compile libbrotli statically into curl-impersonate

Dockerfile.template, chrome/Dockerfile, generate_dockerfiles.sh
Since the firefox and chrome builds are similar except for the TLS
library used, it makes sense to unify their Dockerfiles. This commit
introduces a template Dockerfile from which both the build Dockerfiles
are generated using the simple 'mustache' template system.
=> Use a template for generating Dockerfiles

.github/workflows/publish-docker-image.yml, Dockerfile.template, README.md, chrome/Dockerfile.alpine, firefox/Dockerfile, firefox/Dockerfile.alpine, generate_dockerfiles.sh, tests/README.md
* Add Dockerfiles to create a minimal Alpine Linux image with curl-impersonate.
* Add GitHub action to automatically build and push these images to Docker Hub.
=> Add Alpine Linux images and push automatically to DockerHub

Dockerfile.template, README.md, firefox/Dockerfile, firefox/Dockerfile.alpine, firefox/curl_ff98, firefox/patches/curl-impersonate.patch, tests/signatures.yaml, tests/test_impersonate.py
Add support for impersonating Firefox 98 released a few days ago. It has
the same TLS signature as Firefox 95 so the adaptation includes changing
the user-agent only. Upgrade the NSS version used to 3.75, even though
it's not strictly necessary.
=> Impersonate Firefox 98

README.md, chrome/curl_chrome99_android, chrome/patches/curl-impersonate.patch, tests/signatures.yaml, tests/test_impersonate.py
Add support for impersonating Chrome 99 on Android 12 (Pixel 6 was
chosen as an arbitrary Android phone to impersonate). The TLS signature
for Chrome on Android is identical to Chrome on Windows. The difference
is in a few HTTP headers ('sec-ch-ua-mobile', 'sec-ch-ua-platform' and
'user-agent').
=> Add signature for Chrome 99 on Android

.github/workflows/build-and-test-docker.yml, .github/workflows/build-and-test-make.yml, INSTALL.md, Makefile, Makefile.in, README.md, configure.ac, tests/Dockerfile, tests/conftest.py, tests/test_impersonate.py
Add a Makefile-based build system to allow native builds (without Docker). The Makefile downloads the dependencies, patches them, builds them and then builds curl itself with the needed patches. Documentation is in the new INSTALL.md file.
Fixes #26
=> Native build system using Makefile

chrome/patches/curl-impersonate.patch, firefox/patches/curl-impersonate.patch, tests/test_impersonate.py
Set CURLOPT_ACCEPT_ENCODING to an empty string in
curl_easy_impersonate() to enable decompression of encoded responses
using all built-in compressions. This is similar to adding
'--compressed' in the command line curl and is necessary since
curl_easy_impersonate() adds the 'Accept-Encoding' header which may
cause the server to respond with compressed content.
=> Support encoded content in curl_easy_impersonate

.github/workflows/build-and-test-make.yml, Dockerfile.template, INSTALL.md, Makefile.in, chrome/Dockerfile, chrome/Dockerfile.alpine, chrome/patches/curl-impersonate.patch, chrome/patches/libnghttp2-pc.patch, firefox/Dockerfile, firefox/Dockerfile.alpine, firefox/patches/curl-impersonate.patch, firefox/patches/libnghttp2-pc.patch
Initial attempt at supporting macOS build with the Makefile. Seems to work with the Chrome version for now.
The Firefox version requires more work - linking NSS statically on macOS doesn't currently work since the linker doesn't support the flags that we currently use.
=> macOS initial support attempt

.github/workflows/build-and-test-docker.yml, .github/workflows/build-and-test-make.yml, Dockerfile.template, INSTALL.md, Makefile.in, README.md, firefox/Dockerfile, firefox/Dockerfile.alpine, firefox/patches/curl-impersonate.patch, tests/pytest.ini, tests/requirements.txt, tests/test_impersonate.py
This is an attmept to link with NSS statically on macOS (both Intel and
Apple M1).
Statically linking with NSS is a total mess and completely
undocumented. There are 20+ .a files to link with, and their linking
order matters. The main reference for this commit is a Mozilla Rust code
responsible for statically linking NSS:
https://github.com/mozilla/application-services/blob/b2690fd2e4cc3e8e10b6868ab0de8b79c89d3a93/components/support/rc_crypto/nss/nss_build_common/src/lib.rs#L94
Unfortunately, even with that in hand, a lot of hacking is needed to
make it all work.
=>  Add support for linking NSS statically on macOS

chrome/patches/curl-impersonate.patch, firefox/patches/curl-impersonate.patch
* Set curl's HTTP/2 window size to match Chrome and Firefox. This
affects the "Window Size Increment" parameter in the WINDOW_UPDATE
HTTP/2 frame sent out by curl, which was different than the one
sent by Chrome or Firefox.
* Set curl's HTTP/2 SETTINGS frame to match Firefox.
=> Improve HTTP/2 impersonation

.github/workflows/build-and-test-make.yml, Makefile.in
To speed up the automatic workflows, attempt to cache the slowest part
of the build, which is compiling the TLS libraries (NSS/BoringSSL).
=> Cache build files during GitHub action workflows

.github/workflows/build-and-test-make.yml, Dockerfile.template, Makefile.in, README.md, firefox/Dockerfile, firefox/Dockerfile.alpine, firefox/curl_ff100, firefox/patches/curl-impersonate.patch, tests/signatures.yaml, tests/test_impersonate.py
Add support for impersonating Firefox 100. The TLS signature is identical to
previous versions of Firefox.
In addition, upgrade NSS (Firefox's TLS library) to version 3.77 used by
Firefox 100. This is not strictly necessary as the previous version used
works just fine, but it's better keep up with the newest version.
=> Add support for impersonating Firefox 100

chrome/patches/curl-impersonate.patch, firefox/patches/curl-impersonate.patch
When reusing a curl handle on which the 'Host' header was explicitly
set, the previously-set header was being kept in use for following
requests.
The issue was in curl-impersonate's merging of user-supplied headers
with its own list of browser headers. The call to
Curl_http_merge_headers() which takes care of this had been placed after
the handling of the host header, which caused the previous one to be
used.
=> Fix bug causing a wrong 'Host' header

README.md, chrome/curl_chrome100, chrome/curl_chrome101, chrome/curl_edge101, chrome/patches/curl-impersonate.patch, tests/signatures.yaml, tests/test_impersonate.py
.. and for Edge 101 as well. The TLS fingerprint is identical to
previous versions. The HTTP headers have the usual differences in the
user agents. One important change though is in the way the HTTP2
SETTINGS frame is formed. Up until Chrome 98, there was an additional
randomly-generated setting in the frame. This seems to have been removed
since. Therefore it was removed from curl-impersonate as well, and
support for Chrome/Edge 98 was deprecated, since supporting both
signatures requires a lot of work.
=> Add impersonation support for Chrome 100 and 101, drop support for Chrome 98

INSTALL.md, Makefile.in, configure.ac
Tweak the curl-impersonate build system to make it work on Red Hat
based systems such as CentOS, Fedora and Amazon Linux.
* Change the Makefile to be more portable with different bash versions.
* Detect whether cmake is 'cmake' or 'cmake3', and whether ninja is
'ninja' or 'ninja-build'.
* Explicitly tell brotli to put its libraries in 'lib' dir, otherwise it
might put them in 'lib64' where curl doesn't find them.
* Add instructions for building curl-impersonate from source on Red Hat
based systems.
=> Fix build system to work on Red Hat-based systems

Makefile.in
Build on macOS is failing due to unknown compiler options previously
added to support gcc 12 on Fedora. Add "-Wno-unknown-warning-option" to
silence this failure.
=> Fix broken clang build on macOS

chrome/patches/curl-impersonate.patch, firefox/patches/curl-impersonate.patch
HTTP/2 includes various settings pertaining to stream priorities. Chrome
and Firefox handle them differently, and this behavior was not mimicked
in curl-impersonate well. With this commit, the stream settings set
by curl-impersonate are identical to the real browsers.
* With Chrome, the default stream weight is 256 and the "exclusive bit"
is set to ON.
* With Firefox, a complex tree of stream dependencies is created
by default using PRIORITY frames. This behavior is now mimicked by
curl-impersonate.
=> Set HTTP/2 stream settings correctly

INSTALL.md
On a very minimal Debian 10 (buster) install, I did not have the `unzip` command line tool installed, so the `make chrome-build` could not extract boringssl. This updates the documentation to also suggest `apt install unzip`
=> Add unzip to dependencies for make chrome-build

.github/workflows/build-and-test-make.yml, README.md
Upload a tar file with libcurl-impersonate compiled for Ubuntu and macOS
automatically for each GitHub release. Previously only a statically
compiled version of the binary curl-impersonate was uploaded.
=> Upload precompiled libcurl impersonate on release

Dockerfile.template, chrome/Dockerfile.alpine, chrome/curl_chrome100, chrome/curl_chrome101, chrome/curl_chrome99, chrome/curl_chrome99_android, chrome/curl_edge101, chrome/curl_edge99, chrome/curl_safari15_3, firefox/Dockerfile.alpine, firefox/curl_ff100, firefox/curl_ff91esr, firefox/curl_ff95, firefox/curl_ff98
This is the recommended approach and it's necessary on systems like NixOS.
See: https://web.archive.org/web/20220617225709/https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my
=> Portable shebangs for better compatibility

README.md, browsers.json
For easier programmatic access from scripts, etc., store the list of
supported browsers in a browsers.json file. For each browser we store
its details (name, version), which curl-impersonate binary is needed
(chrome vs. firefox) and the name of the wrapper script.
=> Store the supported browsers list as a JSON file

README.md
I've created the -bin AUR packages for the pre compiled releases:     
https://aur.archlinux.org/packages/curl-impersonate-bin
https://aur.archlinux.org/packages/libcurl-impersonate-bin
=> Added pre compiled packages to AUR

.github/workflows/publish-docker-image.yml, Dockerfile.template, INSTALL.md, chrome/Dockerfile, chrome/Dockerfile.alpine, firefox/Dockerfile, firefox/Dockerfile.alpine, tests/Dockerfile
Push Debian-based Docker images to DockerHub automatically on each
release. The Debian images are suffixed with "-slim-buster" suffix.
Fixes #93
=> Push Debian-based Docker images to DockerHub

README.md, chrome/patches/curl-impersonate.patch, firefox/patches/curl-impersonate.patch, tests/minicurl.c, tests/test_impersonate.py
Let the user disable the built-in list of HTTP headers when using
libcurl-impersonate, either directly or when replacing it at runtime
with LD_PRELOAD. This is intended to give the user more precise control
over the content and order of the HTTP headers.
To support this, the curl_easy_impersonate() now has an added argument
that can be set to 0, in which case the built-in list of HTTP headers
used by libcurl-impersonate will not be automatically sent. Instead,
the user is expected to supply all the headers by themselves using the
standard CURLOPT_HTTPHEADER libcurl option.
When using LD_PRELOAD to inject libcurl-impersonate, one can disable
the built-in headers by setting the CURL_IMPERSONATE_HEADERS
environment variable to "no".
Fixes #90.
**Please note**: This PR changes the signature …
=> Allow disabling built-in HTTP headers

chrome/patches/curl-impersonate.patch, firefox/patches/curl-impersonate.patch, tests/minicurl.c, tests/test_impersonate.py
When impersonating with libcurl, the built-in user agent used for
impersonation was overriding and useragent the user had set via
CURLOPT_USERAGENT. The fix takes care to specifically handle user agent
set with CURLOPT_USERAGENT and use it instead of the built-in one when
it is supplied.
fixes #51
=> Don't ignore useragent from CURLOPT_USERAGENT

INSTALL.md, README.md
Updates docs (README, INSTALL) with some notes on the required dependencies when using the artifacts outside of the build system.
=> Docs: add notes on dependencies, fix links

README.md, docs/01_GETTING_STARTED.md, docs/02_USAGE.md, docs/03_LIBCURL_IMPERSONATE.md, docs/03_LIBCURL_IMPERSONATE_JS.md, docs/03_LIBCURL_IMPERSONATE_PHP.md, docs/README.md
Add more documentation on the following topics:
* Running `curl-impersonate` from the command line, including changing the HTTP headers when needed.
* Using `libcurl-impersonate` in JS and PHP scripts.
=> Create docs/ folder with initial content

configure, configure.ac
This PR corrects a small typo that caused `--disable-static` (which is a flag some distro packaging systems add by default) to actually enable a static build rather than explicitly disable it
For reference (see warning): https://autotools.info/autoconf/arguments.html#autoconf.adding-options.ac-arg-enable-with
=> Fix --disable-static and --enable-static=no

.github/workflows/publish-docker-image.yml, Dockerfile.template, chrome/Dockerfile, firefox/Dockerfile, tests/Dockerfile
Debian Bullseye was released over a year ago, so I suppose using it as a basis for Docker Debain image makes more sense?
It would also help incorporating it in other images, which rather tend to be based on current stable releases. See e.g. https://github.com/RSS-Bridge/rss-bridge/pull/2941#issuecomment-1208569045
Run and tested locally, seems to work just fine.
=> Dockerfile: use bullseye as Debian base

.github/workflows/build-and-test-make.yml, Makefile.in, README.md, browsers.json, chrome/curl_chrome107, chrome/patches/curl-impersonate.patch, tests/signatures/chrome.yaml, tests/test_impersonate.py
Chrome 107 was recently released. The only difference in signature from previous Chrome versions is that an HTTP2_NO_SERVER_PUSH setting is sent in the HTTP2 SETTINGS frame.
=> Add support for impersonating Chrome 107

Makefile.in, README.md, browsers.json, firefox/curl_ff109, firefox/patches/curl-impersonate.patch, tests/signatures/firefox.yaml, tests/test_impersonate.py
Firefox impersonation was not updated in a long while. Add impersonation for Firefox 109. The TLS signature is identical to previous versions, with the usual changes to the HTTP headers.
Update NSS to the latest version as well, even though it is not strictly necessary for the impersonation.
=> Impersonate Firefox 109

README.md, browsers.json, chrome/curl_chrome110, chrome/patches/curl-impersonate.patch, tests/signature.py, tests/signatures/chrome.yaml, tests/test_impersonate.py
Chrome 110 is out, and uses TLS extension permutation enabled by default. See https://chromestatus.com/feature/5124606246518784. This means that the TLS extension order is randomized in each TLS client hello message.
This PR is based on #142. Since Chrome 110 is already out, the Chrome 109 signature was upgraded to Chrome 110.
=> Impersonate Chrome 110

.github/workflows/build-and-test-make.yml, Makefile.in, chrome/patches/curl-impersonate.patch, firefox/patches/curl-impersonate.patch
Though Raspberry Pi OS supports 64-bit with architecture aarch64, there are still users of the 32-bit OS with architecture armv7l. This change adds cross-compilation targeting the 32-bit armv7l architecture with a few tweaks:
- Patch compilation error due to `easy_lock.h` (this has been fixed upstream in curl 7.85+)
- Extend Makefile to include nss NEON libraries for Firefox build
I built the cross-compiled binaries locally with these changes and tested them on a Raspberry Pi 3b+ running 32-bit Raspbian bullseye.
=> Cross-compile armv7l binaries for 32-bit Raspberry Pi's

docs/02_USAGE.md
This PR fixes a transposition in the usage docs.
=> fix: typo in usage docs

.github/workflows/build-and-test-make.yml, Dockerfile.template, Makefile.in, chrome/Dockerfile, chrome/Dockerfile.alpine, chrome/curl_chrome100, chrome/curl_chrome101, chrome/curl_chrome104, chrome/curl_chrome107, chrome/curl_chrome110, chrome/curl_chrome99, chrome/curl_chrome99_android, chrome/curl_edge101, chrome/curl_edge99, chrome/curl_safari15_3, chrome/curl_safari15_5, chrome/patches/curl-impersonate.patch, firefox/Dockerfile, firefox/Dockerfile.alpine, firefox/patches/curl-impersonate.patch
The new curl version includes bugfixes, new options but mainly websocket support which was long requested in curl-impersonate. This commit attempts to upgrade the baseline curl version to 8.1.1 for the Chrome version.
TODO:
=> Upgrade baseline curl to 8.1.1

.github/workflows/build-and-test-make.yml, Dockerfile.template, Makefile.in, firefox/Dockerfile, firefox/Dockerfile.alpine
The nss version currently in use does not build with gcc 13. Upgrade to nss 3.92.
=> Upgrade nss to 3.92

chrome/curl_chrome100, chrome/curl_chrome101, chrome/curl_chrome104, chrome/curl_chrome107, chrome/curl_chrome110, chrome/curl_chrome116, chrome/curl_chrome99, chrome/curl_chrome99_android, chrome/curl_edge101, chrome/curl_edge99, chrome/curl_safari15_3, chrome/curl_safari15_5, docs/02_USAGE.md, firefox/curl_ff100, firefox/curl_ff102, firefox/curl_ff109, firefox/curl_ff117, firefox/curl_ff91esr, firefox/curl_ff95, firefox/curl_ff98
Remove the --false-start flag completely. In the Chrome version it has no affect, and in the Firefox version it may cause connection errors. This flag doesn't seem to affect TLS or HTTP signatures so is safe to remove.
The flag seems to cause connection errors with some http/2 servers. The server chooses http/2 based on alpn but curl initiates a http/1.1 connection instead. This is an upstream bug in curl that affects us as well.
=> Remove --false-start flag

Dockerfile.template, INSTALL.md, chrome/Dockerfile, chrome/Dockerfile.alpine, firefox/Dockerfile, firefox/Dockerfile.alpine, tests/Dockerfile
Hello,
I noticed some Docker base images were getting a bit old, so:
* Update to current versions: python:3.11-slim-bookworm, debian:bookworm-slim, alpine:3.18
* Reduce size of Debian image (remove apt cache) by 10MB
* ~~Add pipefail (which I needed during test), cf. https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/~~
* And also minor Markdown lint of INSTALL.md
=> Docker update base images

Dockerfile.template, Makefile.in, chrome/Dockerfile, chrome/Dockerfile.alpine, firefox/Dockerfile, firefox/Dockerfile.alpine
Enable curl's websocket handling with --enable-websockets.
=> Build curl with websocket support

Dockerfile.template, chrome/Dockerfile, chrome/Dockerfile.alpine, firefox/Dockerfile, firefox/Dockerfile.alpine
The Docker image first builds a static curl-impersonate, then builds libcurl-impersonate separately. However, the second build overrode the binary created in the first one, and was configured without websocket support in addition. This commit fixes both:
* The second build does not override the first, static build.
* The second build is configured with websockets.
Fixes #212
=> Fix Docker build missing websocket support
